# Generated by Django 2.2.12 on 2020-05-18 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siteconfig', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('rank', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('sku', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('title', models.TextField(blank=True, default='', null=True)),
                ('meta_description', models.TextField(blank=True, default='', null=True)),
                ('keywords', models.TextField(blank=True, default='', null=True)),
                ('images', models.TextField(blank=True, default='', null=True)),
                ('markdown', models.TextField(blank=True, default='', null=True)),
                ('html', models.TextField(blank=True, default='', null=True)),
                ('rank', models.IntegerField(default=100)),
                ('hide_shop', models.BooleanField(default=False)),
                ('hide_ads', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_products', to='ecommerce.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('rank', models.IntegerField(default=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('image', models.TextField(default='')),
                ('cardtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('quantity_available', models.IntegerField(blank=True, default=0, null=True)),
                ('is_shop', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=False)),
                ('rank', models.IntegerField(default=0)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ecommerce.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ecommerce.Product')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagprods', to='siteconfig.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat_products', to='ecommerce.SubCategory'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('prod', 'name'), name='prod_variant'),
        ),
        migrations.AddConstraint(
            model_name='producttag',
            constraint=models.UniqueConstraint(fields=('tag', 'prod'), name='prod_tag'),
        ),
    ]
