# Generated by Django 2.2.12 on 2020-05-09 14:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('ecommerce', '0001_initial'), ('ecommerce', '0002_delete_page'), ('ecommerce', '0003_product_productvariant'), ('ecommerce', '0004_auto_20200502_2047'), ('ecommerce', '0005_auto_20200502_2100'), ('ecommerce', '0006_auto_20200502_2110'), ('ecommerce', '0007_auto_20200502_2111'), ('ecommerce', '0008_product_meta_description'), ('ecommerce', '0009_remove_productvariant_sku'), ('ecommerce', '0010_auto_20200503_1115'), ('ecommerce', '0011_product_html'), ('ecommerce', '0012_product_markdown'), ('ecommerce', '0013_auto_20200509_1911'), ('ecommerce', '0014_auto_20200509_1946')]

    initial = True

    dependencies = [
        ('siteconfig', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('sku', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('title', models.TextField(blank=True, default='', null=True)),
                ('keywords', models.TextField(blank=True, default='', null=True)),
                ('rank', models.IntegerField(default=0)),
                ('hide_shop', models.BooleanField(default=False)),
                ('hide_ads', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('meta_description', models.TextField(blank=True, default='', null=True)),
                ('html', models.TextField(blank=True, default='', null=True)),
                ('markdown', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('cardtitle', models.CharField(max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('quantity_available', models.IntegerField(default=0)),
                ('in_stock', models.BooleanField(default=False)),
                ('rank', models.IntegerField(default=0)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ecommerce.Product')),
                ('image', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ecommerce.Product')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagprods', to='siteconfig.Tag')),
            ],
            options={
                'unique_together': set(),
            },
        ),
        migrations.AddConstraint(
            model_name='producttag',
            constraint=models.UniqueConstraint(fields=('tag', 'prod'), name='prod_tag'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('prod', 'name'), name='prod_variant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
