# Generated by Django 2.2.12 on 2020-05-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0002_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('sku', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('keywords', models.TextField(default='')),
                ('rank', models.IntegerField(default=0)),
                ('hide_shop', models.BooleanField(default=False)),
                ('hide_ads', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image_url', models.CharField(max_length=300)),
                ('cardtitle', models.CharField(max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('sku', models.CharField(max_length=30, unique=True)),
                ('price', models.IntegerField()),
                ('quantity_available', models.IntegerField(default=0)),
                ('in_stock', models.BooleanField(default=False)),
                ('rank', models.IntegerField(default=0)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product')),
            ],
        ),
    ]
