# Generated by Django 2.2.12 on 2020-05-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20200523_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='cardname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
