# Generated by Django 2.2.12 on 2020-05-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20200509_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_shop',
            field=models.BooleanField(default=False),
        ),
    ]
