# Generated by Django 2.2.12 on 2020-05-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_productvariant_cardname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shortname',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
