# Generated by Django 2.2.12 on 2020-06-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_product_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='h1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='html',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='markdown',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='h1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='html',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='keywords',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='markdown',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meta_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
