# Generated by Django 2.2.12 on 2020-05-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_productvariant_is_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='cardtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='quantity_available',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
