# Generated by Django 2.2.12 on 2020-05-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20200510_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rank',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='rank',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='rank',
            field=models.IntegerField(default=100),
        ),
    ]
