# Generated by Django 2.2.12 on 2020-05-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20200502_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
