# Generated by Django 2.2.12 on 2020-05-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_product_meta_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
    ]
