# Generated by Django 2.2.12 on 2020-05-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20200503_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='html',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
