# Generated by Django 2.2.12 on 2020-05-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_product_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='markdown',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
