# Generated by Django 2.2.12 on 2020-05-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_product_markdown'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttag',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='producttag',
            constraint=models.UniqueConstraint(fields=('tag', 'prod'), name='prod_tag'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('prod', 'name'), name='prod_variant'),
        ),
    ]
