# Generated by Django 2.1.3 on 2018-11-27 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cart_state', models.CharField(choices=[('C', 'Cart'), ('A', 'Address'), ('P', 'Payment'), ('D', 'Done')], default='C', max_length=3)),
                ('address_name', models.CharField(default='', max_length=100)),
                ('address1', models.CharField(default='', max_length=100)),
                ('address2', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zipcode', models.CharField(default='', max_length=6)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('paymode', models.CharField(blank=True, choices=[('COD', 'Cash on Delivery'), ('PayTM', 'PayTM'), ('PayU', 'PayU Money'), ('InstaM', 'Instamojo')], max_length=10, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('img_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Image')),
            ],
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ImageData')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order_state', models.CharField(choices=[('P', 'Processing'), ('PS', 'Preparing Shipment'), ('S', 'Shipped'), ('D', 'Delivered'), ('C', 'Cancelled')], default='P', max_length=3)),
                ('paymode', models.CharField(choices=[('COD', 'Cash on Delivery'), ('PayTM', 'PayTM'), ('PayU', 'PayU Money'), ('InstaM', 'Instamojo')], max_length=10)),
                ('delivery_charge', models.IntegerField()),
                ('extra_charge', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('courier', models.CharField(default='', max_length=100)),
                ('tracking_no', models.CharField(default='', max_length=100)),
                ('address_name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=6)),
                ('mobile', models.CharField(max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('pagetitle', models.CharField(max_length=50)),
                ('cardtitle', models.CharField(max_length=24)),
                ('price', models.IntegerField()),
                ('mrp_price', models.IntegerField()),
                ('quantity_available', models.IntegerField(default=0)),
                ('in_stock', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('html', models.TextField()),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('type', models.CharField(choices=[('M', 'Menu'), ('S', 'Section'), ('T', 'Tag')], max_length=3)),
                ('is_standalone', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('img_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Image')),
            ],
        ),
        migrations.CreateModel(
            name='UserCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=6, unique=True)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='producttags',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Tags'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderprods', to='products.Orders'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='prod_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
        migrations.AddField(
            model_name='mainimage',
            name='prod_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mainimage', to='products.Product'),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagesdata', to='products.Product'),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='th_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_data_home', to='products.Thumbnail'),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='th_micro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_data_micro', to='products.Thumbnail'),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='th_mini',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_data_mini', to='products.Thumbnail'),
        ),
        migrations.AddField(
            model_name='image',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='prod_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='cartobjects',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='producttags',
            unique_together={('prod_id', 'tag_id')},
        ),
    ]
