# Generated by Django 2.1.3 on 2018-11-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='to_be_order_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
