# Generated by Django 2.1.3 on 2018-11-30 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_cart_to_be_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaytmHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_amount', models.FloatField()),
                ('txn_date', models.DateTimeField()),
                ('txn_id', models.CharField(max_length=400)),
                ('status', models.CharField(max_length=40)),
                ('paytm_orderid', models.CharField(max_length=40)),
                ('order_id', models.CharField(max_length=40)),
                ('currency', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_amount',
            field=models.FloatField(default=0),
        ),
    ]
