# Generated by Django 2.2 on 2020-04-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_mobile_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=3000)),
                ('mmid', models.CharField(default='', max_length=80, null=True)),
                ('csrf_token', models.CharField(default='', max_length=250, null=True)),
                ('referer', models.CharField(default='', max_length=3000, null=True)),
                ('remote_addr', models.CharField(default='', max_length=250, null=True)),
                ('visited', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
