# Generated by Django 2.1.3 on 2018-12-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20181201_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=101, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
