# Generated by Django 2.1.3 on 2018-12-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qrcode',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
