# Generated by Django 2.1.3 on 2018-12-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qrcode',
        ),
    ]
