# Generated by Django 2.1.3 on 2018-12-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pagetitle',
            field=models.CharField(max_length=100),
        ),
    ]
