# Generated by Django 2.1.3 on 2019-01-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20181213_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email_sent_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='email_sent_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='email_sent_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
