# Generated by Django 2.1.3 on 2019-02-03 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190123_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SimilarProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='free_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='similarproducts',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simprods', to='products.Product'),
        ),
        migrations.AddField(
            model_name='similarproducts',
            name='sim_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.Product'),
        ),
        migrations.AddField(
            model_name='relatedproducts',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relprods', to='products.Product'),
        ),
        migrations.AddField(
            model_name='relatedproducts',
            name='sim_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.Product'),
        ),
    ]
