# Generated by Django 2.1.3 on 2019-02-08 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20190205_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainimage',
            name='thumb_data',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.ImageData'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_google',
            field=models.BooleanField(default=False),
        ),
    ]
