# Generated by Django 2.1.3 on 2019-03-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_usercode_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='product_head',
            field=models.CharField(default='', max_length=300),
        ),
    ]
