# Generated by Django 2.1.3 on 2019-03-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_shoplinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ShopLinks')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoplinks', to='products.Product')),
            ],
        ),
    ]
