# Generated by Django 2.1.3 on 2019-03-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplinks',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
