# Generated by Django 2.1.3 on 2019-04-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_shoplinks_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cardtitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='pagetitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
