# Generated by Django 2.1.3 on 2019-04-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20190415_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplinks',
            name='meta_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='shoplinks',
            name='meta_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
