# Generated by Django 2.1.3 on 2019-04-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20190416_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreadCrumbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BreadEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bread_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breadentries', to='products.BreadCrumbs')),
            ],
        ),
        migrations.AddField(
            model_name='shoplinks',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='breadentry',
            name='link_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ShopLinks'),
        ),
        migrations.AddField(
            model_name='product',
            name='breadcrumb',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.BreadCrumbs'),
        ),
        migrations.AddField(
            model_name='shoplinks',
            name='breadcrumb',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.BreadCrumbs'),
        ),
    ]
