# Generated by Django 2.1.3 on 2019-04-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20190416_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordtags',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
