# Generated by Django 2.1.3 on 2019-05-16 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20190416_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferalCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('referer', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=400)),
                ('is_shipping_free', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferalPriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('moq', models.IntegerField()),
                ('code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ReferalCodes')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='is_referal_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='referal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='referal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cart',
            name='referal_obj',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ReferalCodes'),
        ),
    ]
