# Generated by Django 2.1.3 on 2019-06-23 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0032_blog_blogphotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazopayIDMaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_id', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RazorpayHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=40)),
                ('txn_amount', models.FloatField()),
                ('txn_date', models.DateTimeField()),
                ('status', models.CharField(max_length=40)),
                ('details', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='paymode',
            field=models.CharField(blank=True, choices=[('COD', 'Cash on Delivery'), ('PayTM', 'PayTM'), ('PayU', 'PayU Money'), ('InstaM', 'Instamojo'), ('RAZORPAY', 'RAZORPAY')], max_length=10, null=True),
        ),
    ]
