# Generated by Django 2.1.3 on 2019-06-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20190623_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogphotos',
            name='main_image',
            field=models.BooleanField(default=False),
        ),
    ]
