# Generated by Django 2.1.3 on 2019-06-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20190625_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hide_description',
            field=models.BooleanField(default=False),
        ),
    ]
