# Generated by Django 2.1.3 on 2019-07-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_product_hide_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='keywords',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
