# Generated by Django 2.1.3 on 2019-08-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20190727_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ip_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orders',
            name='ip_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usercode',
            name='ip_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
