# Generated by Django 2.1.3 on 2019-09-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20190817_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hide_shop',
            field=models.BooleanField(default=False),
        ),
    ]
