# Generated by Django 2.2 on 2020-04-18 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
