# Generated by Django 2.2 on 2020-04-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='config',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='keywords',
            field=models.CharField(default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
