# Generated by Django 2.2 on 2020-04-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200419_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='config',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='page',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, default='', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
