# Generated by Django 2.2 on 2020-04-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200419_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='h1',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
