# Generated by Django 2.2.12 on 2020-05-18 16:37

from django.db import migrations, models
import django.utils.timezone
import orders_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=orders_app.models.generate_uuid, max_length=100)),
                ('is_unsubscribed', models.BooleanField(default=False)),
                ('is_invalid', models.BooleanField(default=False)),
                ('is_bounced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile', models.CharField(default='', max_length=20)),
                ('token', models.CharField(default=orders_app.models.generate_uuid, max_length=100)),
                ('is_unsubscribed', models.BooleanField(default=False)),
                ('is_invalid', models.BooleanField(default=False)),
                ('is_bounced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=orders_app.models.generate_uuid, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
